config/routes.rb
BackBoneDemo::Application.routes.draw do
  resources :employees

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates_presence_of :name, :age
  validates_numericality_of :age, :only_integer => true, :greater_than_or_equal_to => 18, :less_than_or_equal_to => 65
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.order(sort_column + " " + sort_direction)

    if params[:format] == 'csv'
      @employees = @employees.where("(id >= #{params[:from].present? ? params[:from] : 1}) AND (id <= #{params[:to].present? ? params[:to] : Employee.last.id})")
      generate_csv_headers("negotiations-#{Time.now.strftime("%Y%m%d")}")
    else
      @employees = @employees.paginate(:per_page => 5, :page => params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.csv
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :ok }
    end
  end

  def generate_csv_headers(filename)
    headers.merge!({
      'Cache-Control'             => 'must-revalidate, post-check=0, pre-check=0',
      'Content-Type'              => 'text/csv',
      'Content-Disposition'       => "attachment; filename=\"#{filename}\"",
      'Content-Transfer-Encoding' => 'binary'
    })
  end

  def sort_column
    Employee.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :student %><br />
    <%= f.check_box :student %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.csv.erb
<% require 'csv' %>
<%- headers = ["Id", "Name", "Age", "Nickname", "Student"] -%>
<%= CSV.generate_line headers %>
<%- @employees.each do |n| -%>
<%- row = [ n.id,
            n.name,
            n.age,
            n.nickname,
            n.student ] -%>
<%=   CSV.generate_line row %>
<%- end -%>

app/views/employees/index.html.erb
<div id="content">
    <div id="add_div" align="center"></div>
    <div id="errors"></div>
  <hr/>
    <div id="employees" align="center"></div>
    <div id="pagination">
        <%= will_paginate @epmloyees %>
    </div>
  <hr/>
    <div id="csv_export" align="center">
      <h3>Data export (please enter records numbers interval)</h3>
      <%= form_tag({ :format => :csv }, {:method => :get, :class => :csv_form }) do %>
        <div class="field">
          <div><%= label_tag :from, "start from(#)" %></div>
          <div><%= text_field_tag :from, "" %></div>
        </div>
        <div class="field">
          <div><%= label_tag :to, "end with(#)" %></div>
          <div><%= text_field_tag :to, "" %></div>
        </div>

        <div class="field">
          <div>.</div>
          <div><%= submit_tag "Export" %></div>
        </div>
      <% end %>
    </div>
</div>
<script type="text/javascript">
  $(function() {
    window.router = new BackBoneDemo.Routers.EmployeesRouter({employees: <%= @employees.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>

app/views/employees/index.js.erb
window.router = new BackBoneDemo.Routers.EmployeesRouter({employees: <%= @employees.to_json.html_safe -%>});
window.router.index();
$("#pagination").html("<%= escape_javascript(will_paginate @employees) %>");

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Age:</b>
  <%= @employee.age %>
</p>

<p>
  <b>Nickname:</b>
  <%= @employee.nickname %>
</p>

<p>
  <b>Student:</b>
  <%= @employee.student %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackBoneDemo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>